# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 677755f1e9b5e77f9f6db60b7aabde26950a330705465b4f7fa3831fb6f91f66e6b5fc45c0d4179a106fd7be3192ca347fb9535956495dc924ef017b92620b04

test:
  secret_key_base: f585149fb9e64441713891d7b83e5b4d732c4277993cdad2e824f35945f3c2fe78d390f41be215f900909b5ec96a480acc4fc577a449c7187912543fa2564578

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
